import { ThemeProvider } from './context/ThemeContext'
import Navbar from './components/Navbar'
import Hero from './components/Hero'
import Overview from './components/Overview'
import DataCleaning from './components/DataCleaning'
import PythonAnalysis from './components/PythonAnalysis'
import SqlReporting from './components/SqlReporting'
import Dashboard from './components/Dashboard'
import BusinessInsights from './components/BusinessInsights'
import ProjectStory from './components/ProjectStory'
import TechStack from './components/TechStack'
import Footer from './components/Footer'
import { useEffect, useState } from 'react'

export default function App() {
  const [data, setData] = useState(null)
  const [error, setError] = useState(null)

  useEffect(() => {
    fetch(`${import.meta.env.BASE_URL}data/analytics.json`)
      .then((r) => {
        if (!r.ok) throw new Error('Failed to load analytics data')
        return r.json()
      })
      .then(setData)
      .catch((e) => setError(e.message))
  }, [])

  return (
    <ThemeProvider>
      <div className="relative min-h-screen">
        <div className="pointer-events-none fixed inset-0 grid-bg opacity-60" />
        <div className="relative z-10">
          <Navbar />
          {error ? (
            <div className="max-w-3xl mx-auto mt-32 p-6 card text-center">
              <p className="text-brand-400 font-semibold">Error: {error}</p>
              <p className="text-sm opacity-70 mt-2">
                Make sure <code>data/analytics.json</code> is generated by running{' '}
                <code>python analyze.py</code>.
              </p>
            </div>
          ) : !data ? (
            <div className="flex items-center justify-center min-h-[60vh]">
              <div className="card px-6 py-4 flex items-center gap-3">
                <div className="h-2 w-2 rounded-full bg-accent-400 animate-pulse" />
                <span className="text-sm opacity-80">Loading analytics bundle…</span>
              </div>
            </div>
          ) : (
            <>
              <Hero overview={data.overview} />
              <Overview overview={data.overview} />
              <DataCleaning cleaning={data.cleaning} />
              <PythonAnalysis data={data} />
              <SqlReporting data={data} />
              <Dashboard data={data} />
              <BusinessInsights insights={data.insights} overview={data.overview} />
              <ProjectStory overview={data.overview} />
              <TechStack />
              <Footer />
            </>
          )}
        </div>
      </div>
    </ThemeProvider>
  )
}
